# Generated by Django 4.2.13 on 2026-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('resilience_score', models.IntegerField()),
                ('slope_risk', models.BooleanField(default=False)),
                ('drainage_quality', models.CharField(max_length=20)),
                ('income_level', models.CharField(max_length=20)),
                ('historical_events', models.IntegerField(default=0)),
                ('slope_percentage', models.IntegerField(default=0)),
                ('current_risk_level', models.IntegerField(default=0)),
                ('current_risk_probability', models.FloatField(default=0.0)),
                ('current_precip_6h', models.FloatField(default=0.0)),
                ('current_pressure_trend', models.FloatField(default=0.0)),
                ('current_humidity', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
